delivery/rails_app/config/routes.rb
RailsApp::Application.routes.draw do
  resources :transaction do
    collection do
      put 'assign'
    end
    member do
      get 'split'
      put 'save_splits'
    end
  end
  resources :deposit
  resources :category, format: :json, only: [:index]
  get '/admin' => 'admin#index'
  post '/admin' => 'admin#save'

  get '/:month(/:year)' => 'dashboard#month'
  root to: 'dashboard#home'

end

delivery/rails_app/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @accounts = GetAccountBalances.new(gateway).run
    @balances = GetCategoryBalances.new(gateway).run
  end

  def save
    case params[:commit]
    when "Add Account"
      save_account
    when "Add Category"
      save_category
    end

    redirect_to :action => :index
  end

  def save_account
    account_info = { name: params[:new_account_name], balance: params[:new_account_balance] }
    CreateAccount.new(gateway).run account_info
  end

  def save_category
    category_info = { name: params[:new_category_name], budget: params[:new_category_budget] }
    CreateCategory.new(gateway).run category_info
  end
end

delivery/rails_app/app/controllers/application_controller.rb
require 'gateway_factory'
require 'finances'
class ApplicationController < ActionController::Base
  include Finances
  protect_from_forgery

  helper_method :gateway, :to_date

  def gateway
    ::GatewayFactory.create ENV["RAILS_ENV"]
  end

  def to_date month='', year=''
    year = Integer(year) rescue nil
    month = Date::MONTHNAMES.index(month) || Date::ABBR_MONTHNAMES.index(month)
    if month and year
      Date.new(year, month, 1).to_time
    end
  end
end

delivery/rails_app/app/controllers/category_controller.rb
class CategoryController < ApplicationController
  respond_to :json
  def index
    @categories = GetCategoryBalances.new(gateway).run
    @categories = @categories.map { |key, value| Hash[:name, key, :amount, value] }
    respond_with @categories
  end

end

delivery/rails_app/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def home
    @balances = GetCategoryBalances.new(gateway).run
    @accounts = GetAccountBalances.new(gateway).run
    @unsorted_transactions = GetUnsortedTransactionAccountSummary.new(gateway).run
  end

  def month
    @categories = GetCategoryBalanceSheet.new(gateway).run params
    @accounts = GetAccountBalanceSheet.new(gateway).run params
    @totals = GetBalanceSheetTotals.new(gateway).run params
    @expenses = GetExpenseBalanceSheet.new(gateway).run params
    @month = Date.strptime("#{params[:year] || Date.today.year }-#{params[:month]}", '%Y-%B')
  end
end

delivery/rails_app/app/controllers/deposit_controller.rb
class DepositController < ApplicationController
  def index
    @deposits = GetDeposits.new(gateway).run
  end

  def edit
    transaction_id = params[:id].to_i
    @deposit = index.find { |t| t[:id] == transaction_id  }
    @credits = GetCredits.new(gateway).run(transaction_id: transaction_id)
    apply_date = @deposit[:posted_at].next_month
    @applied_year = apply_date.year
    @applied_month = apply_date.strftime '%B'
  end

  def update
    h = { credits: [],
          transaction_id: params[:id].to_i,
          date_applied: to_date(params[:applied_month], params[:applied_year])
    }
    params[:category] ||= []
    params[:category].reject { |c| c.blank? }.each_with_index do |category, index|
      amount = params[:amount][index].to_i
      h[:credits] << { category: category, amount: amount}
    end

    DistributeDeposit.new(gateway).run(h)
    redirect_to :action => :edit
  end
end

delivery/rails_app/app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
  def index
    @unsorted_transactions = GetUnsortedExpenses.new(gateway).run
  end

  def assign
    if(params[:split])
      redirect_to split_transaction_path(params[:transaction_id])
    else
      AssignTransaction.new(gateway).run(params)
      redirect_to :action => :index
    end
  end

  def split
    @transaction = GetTransaction.new(gateway).run(params)
  end

  def save_splits
    h = {}
    h[:debits] = []
    h[:transaction_id] = params[:id]
    params[:category].each_with_index do |category, index|
      amount = params[:amount][index]
      unless amount.split.empty?
        h[:debits] << { category: category, amount: amount}
      end
    end
    SplitTransaction.new(gateway).run(h)
    redirect_to :action => :index
  end
end

delivery/rails_app/app/helpers/application_helper.rb
module ApplicationHelper
end

delivery/rails_app/app/helpers/dashboard_helper.rb
module DashboardHelper
  def this_month_string
    month_string @month
  end

  def link_to_prev_month(options={})
    link_to_month(@month.prev_month, options)
  end

  def link_to_next_month(options={})
    link_to_month(@month.next_month, options)
  end

  def link_to_month(date, options={})
    link_to "#{month_string date}", month_path(date), options
  end

  def month_path(date)
    "/#{month_string date}/#{date.strftime("%Y")}"
  end 

  def month_string(date)
    "#{date.strftime('%B')}"
  end
end

delivery/rails_app/app/helpers/deposit_helper.rb
module DepositHelper
end

delivery/rails_app/app/helpers/transaction_helper.rb
module TransactionHelper
end

delivery/rails_app/app/views/admin/index.html.erb
<%= form_tag do %>
  <div class="row">
    <div class="span8">
      <h2>Accounts</h2>
      <table id=accounts class="table table-striped">
        <% @accounts.each_pair do |key, value| %>
          <tr>
            <td><div><%=key%></div></td>
            <td><div id=<%=key%>_balance><%=value%></div></td>
          </tr>
        <% end %>
      </table>
      <table class="table">
        <tr>
          <td><%= text_field_tag(:new_account_name) %></td>
          <td><%= text_field_tag(:new_account_balance) %></td>
          <td><%= submit_tag "Add Account", class: "btn"  %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="span8">
      <h2>Categories</h2>
      <table id=category_balances class="table table-striped">
        <% @balances.each_pair do |key, value| %>
          <tr>
            <td><div><%=key%></div></td>
            <td><div id=<%=key%>_balance><%=value%></div></td>
          </tr>
        <% end %>
      </table>
      <table class="table">
        <tr>
          <td><%= text_field_tag(:new_category_name) %></td>
          <td><%= text_field_tag(:new_category_budget) %></td>
          <td><%= submit_tag "Add Category", class: "btn"  %></td>
        </tr>
      </table>
    </div>
  </div>
<% end %>

delivery/rails_app/app/views/dashboard/home.html.erb
<div class="row">
  <div class="span4">
    <table id=account_balances class="table table-striped">
      <% @accounts.each_pair do |key, value| %>
        <tr>
          <td><div><%=key%></div></td>
          <td><div id=<%=key%>_balance><%=value%></div></td>
        </tr>
        <% if @unsorted_transactions[key] %>
          <% text = "#{key} has #{@unsorted_transactions[key][:count]} unsorted transactions totaling $#{@unsorted_transactions[key][:amount]}" %>
          <tr>
            <td colspan=2><div id=<%=key%>_unsorted><%=link_to text, transaction_index_path %></div></td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>
  <div class="span4">
    <table id=category_balances class="table table-striped">
      <% @balances.each_pair do |key, value| %>
        <tr>
          <td><div><%=key%></div></td>
          <td><div id=<%=key%>_balance><%=value%></div></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

delivery/rails_app/app/views/dashboard/month.html.erb
<% provide(:title, this_month_string) %>
<div class="span8">
  <div class="row text-center page-header">
    <h2><small> <%= link_to_prev_month :id => 'previous_month' %> </small>
      <%= "#{this_month_string}" %>
      <small><%= link_to_next_month :id => 'next_month' %> </small>
    </h2>
  </div>
  <div class="row">
    <div class="span4">
      <div class ="row text-center">Categories</div>
      <div class="row">
      <table id=categories class="table table-striped">
        <% @categories.each do |category| %>
          <tr>
            <td class='category'><%= category[:category] %></td>
            <td class='budget'><%= category[:budget] %></td>
            <td class='spent'><%= category[:spent] %><td>
            <td class='remainder'><%= category[:remainder] %></td>
          </tr>
        <% end %>
      </table>
    </div>
    </div>
    <div class="span4">
      <div class ="row text-center">Accounts</div>
      <div class="row">
      <table id=accounts class="table table-striped">
        <% @accounts.each do |account| %>
          <tr>
            <td class='account'><%= account[:account] %></td>
            <td class='starting'><%= account[:starting] %></td>
            <td class='ending'><%= account[:ending] %><td>
            <td class='change'><%= account[:change] %></td>
          </tr>
        <% end %>
      </table>
    </div>
    </div>
  </div>
  <div class="row">
    <table id=expenses class="table table-striped">
      <% @expenses.each do |expense| %>
        <tr>
          <td class='amount'><%= expense[:amount] %></td>
          <td class='description'><%= expense[:description] %></td>
          <td class='category'><%= expense[:category] %></td>
          <td class='date'><%= expense[:date] %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="row">
    <table id=totals class="table table-striped">
      <tr>
        <td>Deposits</td>
        <td id='total_deposits'><%= @totals[:credits] %></td>
        <td>Expenses</td>
        <td id='total_expenses'><%= @totals[:debits] %></td>
      </tr>
    </table>
  </div>
</div>

delivery/rails_app/app/views/deposit/edit.html.erb
<% content_for(:head) do %>
  <script type="text/javascript">
    <%= render :partial => "transaction/split_transaction.js.erb", :formats => :js, :handlers => [:erb, :js] %>
  </script>
<% end %>

<h2>Distribute Your Deposit</h2>

<div class="row">
  <%= form_tag( {:action => "update"}, {:method => "put"}) do %>
    <div class="span2">Apply to</div>
    <div class="span6">
      <%= text_field_tag :applied_month, @applied_month %>
      <%= text_field_tag :applied_year, @applied_year %>
    </div>
    <div class="span8">
      <table id=split_transactions class="table table-striped">
        <tr>
          <th><%= @deposit[:description] %></th><th><h3>$<span id="transaction_amount"><%= @deposit[:amount] %></span></h3></th>
        </tr>
        <tr class='debit_row'/>
        <% @credits.each do |credit| %>
          <%= render partial: "transaction/debit_row", locals: {category: credit[:category], amount: credit[:amount]} %>
        <% end %>
        <tr>
          <td>Remainder</td><td>$<span id="remainder"><%= @deposit[:amount] %></span></td>
        </tr>
      </table>
      <%= submit_tag "Save", name: 'split', class: "btn"  %>
      <%= button_tag "Cancel", type: 'button', class: "btn", onclick: "location.href = '#{transaction_index_path()}'" %>
    <% end %>
  </div>

</div>

delivery/rails_app/app/views/deposit/index.html.erb
<div class="row">
  <div class="span4">
    <table id=deposits class="table table-bordered">
      <% @deposits.each do |t| %>
        <tr id=deposit_<%= t[:id] %>>
          <td> <%= link_to t[:description], edit_deposit_path(t[:id]) %></td><td class='amount'> <%=t[:amount] %> </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

delivery/rails_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Dashboard", root_path %> </li>
          <li><%= link_to "Income", deposit_index_path %> </li>
          <li><%= link_to "Expenses", transaction_index_path %> </li>
          <li><%= link_to "Getting Started", admin_path %> </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

delivery/rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finances | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield(:head) -%>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

delivery/rails_app/app/views/transaction/_debit_row.html.erb
<tr class='debit_row'>
  <% category = local_assigns[:category] %>
  <% amount = local_assigns[:amount]  %>
  <td><%= text_field_tag 'category[]', category, class: 'category' %></td>
  <td><%= number_field_tag 'amount[]', amount, class: 'amount' %></td>
  <td><%= link_to_function(image_tag('plus.png'), 'window.split.add()') %> </td>
  <td><%= link_to_function(image_tag('delete.png'), 'window.split.delete($(this))') %> </td>
</tr>

delivery/rails_app/app/views/transaction/_split_transaction.js.erb
$(document).ready(function() {
    if ($('table#split_transactions').length) {
      split.bindFunctions();
      split.add();
      split.calculateRemainder();
    }
});

(function(split, $, undefined ) {
  split.bindFunctions = function() {
    $('table#split_transactions').on('change', 'input.amount', function(){
      split.calculateRemainder();
    });
  };
    
  split.add = function() {
    var row = '<%= escape_javascript(render(partial: "transaction/debit_row")) %>';
    $('#split_transactions tr.debit_row:last').after(row);
  };

  split.delete = function($element) { 
    $element.closest('tr').remove();
    split.calculateRemainder();
  }

  split.calculateRemainder = function() {
    var remainder = parseInt($('#transaction_amount').text(), 10);
    $('input.amount').each(function( index ) {
    val = $(this).val();
    if(!val) {
        val = 0;
      }
      remainder -= parseInt(val, 10);
    });

    $('#remainder').text(remainder);
  }

}( window.split = window.split || {}, jQuery ));

delivery/rails_app/app/views/transaction/index.html.erb
<div class="row">
  <div class="span4">
    <table id=unsorted_transactions class="table table-bordered">
      <% @unsorted_transactions.each_pair do |account, account_transactions| %>
        <tr><th><%= account[:name] %></th></tr>
        <% account_transactions.each do |t| %>
          <tr id=t<%= t[:id] %> class='transaction_row'>
            <td> <%=t[:description] %></td><td class='amount'> <%=t[:amount] %> </td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>
  <div class="span5 sidebar-fixed">
    <%= form_tag( {:action => "assign"}, {:method => "put"}) do %>
      <%= text_field_tag :category, nil, class: 'typeahead' %>
      <%= hidden_field_tag :transaction_id %>
      <%= hidden_field_tag :amount %>
      <%= submit_tag "Assign", name: 'assign', class: "btn btn-top"  %>
      <%= submit_tag "Split",  name: 'split',  class: "btn btn-top"  %>
    <% end %>
  </div>

</div>

delivery/rails_app/app/views/transaction/split.html.erb
<% content_for(:head) do %>
  <script type="text/javascript">
    <%= render :partial => "split_transaction", :formats => :js, :handlers => [:erb, :js] %>
  </script>
<% end %>

<h2>Split Your Transaction</h2>
<div class="row">
  <div class="span8">
      <%= form_tag( {:action => "save_splits"}, {:method => "put"}) do %>
        <table id=split_transactions class="table table-striped">
           <tr>
             <td><h3><%= @transaction[:description] %></h3><td><h3>$<span id="transaction_amount"><%= @transaction[:amount] %></span></h3></td>
            </tr>
            <tr class='debit_row'/>
            <tr>
              <td>Remainder</td><td>$<span id="remainder"><%= @transaction[:amount] %></span></td>
            </tr>
        </table>
      <%= submit_tag "Save", name: 'split', class: "btn"  %>
      <%= button_tag "Cancel", type: 'button', class: "btn", onclick: "location.href = '#{transaction_index_path()}'" %>
    <% end %>
  </div>

</div>